swagger-api:
  version: "1.0"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/userbook
    username: test
    password: test
  jpa:
    # If we still want to have both Hibernate automatic schema generation
    # in conjugation with script-based schema creation and data population, we'll have to use
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info